#ansible-playbook -i front-dev.dimpul.online, roboshop.yml -e ROLL_NAME=frontend -e ansible_user=centos
#-e ansible_password=DevOps321
- name: roboshop setup
  hosts: all
  #connection: local
  become: yes
  roles:
    - "{{ROLL_NAME}}"