- name: install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

#This task you can give either at end of the "ansible.builtin.copy" also
#- name: start nginx
#  ansible.builtin.systemd:
#      name: nginx
#      state: started
#      enabled: yes

- name: remove old directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: create directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: directory

#- name: Unarchive a roboshop-frontend file
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
#    dest: /usr/share/nginx/html
#    remote_src: yes

- name: Download {{component}} content
  ansible.builtin.unarchive:
    src: http://{{nexus_user}}:{{nexus_user}}@172.31.12.68:8081/repository/${component}/${component}-${app_version}.zip
    dest: /usr/share/nginx/html
    remote_src: yes
  vars:
    nexus_user: "{{ lookup('aws_ssm', 'nexus_user', region='us-east-1' ) }}"
    nexus_pass: "{{ lookup('aws_ssm', 'nexus_pass', region='us-east-1' ) }}"

- name: Copy roboshop.conf file
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: start nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes



