- name: install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: start nginx
  ansible.builtin.systemd:
      name: nginx
      state: started
      enabled: yes

- name: remove old directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: create directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: directory

- name: Unarchive a  roboshop-frontend file
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /tmp/frontend.zip
    remote_src: yes



