- name: download rabbitmq conf
  ansible.builtin.shell: https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash

- name: install erlang
  ansible.builtin.yum:
    name: erlang
    state: installed

- name: download rabbitmq repo
  ansible.builtin.shell: https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: install erlang
  ansible.builtin.yum:
    name: rabbitmq-server
    state: installed

- name: start erlang
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: download rabbitmq repo
  ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123 ; rabbitmqctl set_user_tags roboshop administrator ; rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"