- name: Disable mysql 8 version
  ansible.builtin.shell: dnf module disable mysql -y

- name: Copy mysql.service file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/systemd/system/mysql.service

- name: install mysql
  ansible.builtin.yum:
    name : mysql-community-server
    state: installed

- name: start mysql
  ansible.builtin.systemd:
    name: mysql
    state: started
    enabled: yes

- name: reset default password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass ${root_mysql_password}
  ignore_errors: yes