- name: Add application user
  ansible.builtin.user:
    name: roboshop

- name: remove old directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: create directory
  ansible.builtin.file:
    path: /app
    state: directory

#- name: Download {{component}} content
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
#    dest: /app
#    remote_src: yes

- name: Download {{component}} content
  ansible.builtin.unarchive:
    src: http://172.31.12.68:8081/repository/${component}/${component}-${app_version}.zip
    dest: /app
    remote_src: yes
    vars:
     nexus_user: "{{ lookup('aws_ssm', 'nexus_user', region='us-east-1' ) }}"
     nexus_pass: "{{ lookup('aws_ssm', 'nexus_pass', region='us-east-1' ) }}"