- name: install python deps
  ansible.builtin.yum:
    name:
      - python3-PyMySQL
      - mysql
    state: installed

- name: Load mysql schema
  community.mysql.mysql_db:
    state: present
    name: all
    target: /app/schema/{{component}}.sql
    login_host: mysql-dev.dimpul.online
    login_user: root
    login_password: "{{ root_mysql_password }}"