- name: install nodejs repos
  ansible.builtin.shell: https://rpm.nodesource.com/setup_lts.x | bash

- name: install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Add application user
  ansible.builtin.user:
    name: roboshop

- name: remove old directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: create directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Unarchive a roboshop-cart content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/cart.zip
    dest: /app
    remote_src: yes

- name: install nodejs dependencies
  community.general.npm:
    path: /app
    state: latest

- name: Copy cart.service file
  ansible.builtin.copy:
    src: cart.service
    dest: /etc/systemd/system/cart.service

- name: start cart service
  ansible.builtin.systemd:
    name: cart
    daemon_reload: yes
    enabled: yes
    state: restarted